### ISSUE TITLE
Set schedule repeat bad request

### ISSUE THREAD

**Issue by markblokpoel** [lendy007/homeassistant-skodaconnect#120]
**Describe the bug**
When calling the `set_departure_schedule` with recurring option it fails with a Bad request error. I've tried to narrow down the cause, and I suspect that in `vehicle.py` line 628 should append weekdays (containing full strings) and not days (containing y/n), since I've seen the JSON returning full week days in an array and the data currently send is "['y', 'y', 'y']" when I set it to "yyynnnn".

```
data['timersSettings']['timers'][index]['recurringOn'].append(**week**days[num])
```

```
service: skodaconnect.set_departure_schedule
data:
  id: 1
  time: '06:30'
  enabled: true
  recurring: true
  days: 'yyynnnn'
  temp: 20
  climatisation: true
  device_id: 766f141621621dc3a48546ed99482058
```

**Latest working release**
1.0.67

**Debug logs**

```
2022-05-11 21:25:50 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/TMBJB7NY6NF035846/timers" returned with status code [200]
2022-05-11 21:25:51 DEBUG (MainThread) [skodaconnect.connection] Request failed. Data: {'json': {'type': 'UpdateTimers', 'timersSettings': {'timers': [{'id': 1, 'enabled': True, 'type': 'RECURRING', 'time': '06:30', 'date': '2022-05-12', 'recurringOn': ['y', 'y', 'y']}, {'id': 2, 'enabled': False, 'type': 'ONE_OFF', 'time': '22:00', 'date': '2022-05-13'}]}}}, 
```

**Installation:**

 - Home Assistant variant: Core
 - Python version: 3.9.9
 - Python library versions: skodaconnect 1.1.19

**Additional context**
Using to connect with an Enyaq. Setting single departure schedule works. Let me know if further information / logs are required and if/how I can help test any possible fixes. Thanks a bunch for the awesome libraries!
