### ISSUE TITLE
Friendly name

### ISSUE THREAD

**Issue by siamssi** [lendy007/homeassistant-skodaconnect#3]
Hello I put a friendly name but doesn't work

  name:
        wvw1234567812356: 'Superb'

I have my vin number

![image](https://user-images.githubusercontent.com/47040677/100028111-73036200-2dee-11eb-99ad-8b9ecde0bf11.png)

**Comment by lendy007** [comment]
Can you post your whole skodaconnect config string? For most of the people it is working fine so I suspect some indentation issue...

It should be:
```
skodaconnect:
    username: <username for skoda connect>
    password: <password for skoda connect>
    spin: <S-PIN for skoda connect>
    combustion_engine_heating_duration: <allowed values 10,20,30,40,50,60 (minutes)>
    combustion_engine_climatisation_duration: <allowed values 10,20,30,40,50,60 (minutes)>
    scandinavian_miles: false
    scan_interval:
        minutes: 5
    name:
        wvw1234567812356: 'Kodiaq'
```
