### ISSUE TITLE
v1.0.40-RC5: VW-Group API token could not be verified!

### ISSUE THREAD

**Issue by zipposi** [lendy007/homeassistant-skodaconnect#38]
**Describe the bug**
On starting HA I see this error in the log. I can normally use the web pages and have agreed to the rules.

**Latest working release**
I never succeded to make it work. Vehicle is Skoda Citigoe iv

**Debug logs**
Logger: skodaconnect.connection
Source: /usr/local/lib/python3.8/site-packages/skodaconnect/connection.py:429
First occurred: 7:37:31 PM (1 occurrences)
Last logged: 7:37:31 PM

VW-Group API token could not be verified!

**Installation:**
 - Home Assistant variant: Core, latest version (2020.6.2)
 - Python version: 3.8

**Additional context**

**Comment by Farfar** [comment]
> VW-Group API token could not be verified!

This is a cosmetic issue and won't affect the integration.
If you have issues with the integration I need complete debug logs and I also need to know that your vehicle works in MySkoda app.

**Comment by zipposi** [comment]
Ok, thanks!

But the integration still doesn't work:

In the config file I added this:

```
skodaconnect:
  username: marko@milutinovic.si
  password: xxxxxx
  scandinavian_miles: false
  scan_interval:
    minutes: 1
  name:
    xxx...1234567890: 'Citigo'
```

About the debug logs, are there any instructions how to get them?

The vehicle is visible in the MySkoda app and works flawless.
