### ISSUE TITLE
No way to set charging speed on departure schedules 

### ISSUE THREAD

**Issue by stefanuc111** [lendy007/homeassistant-skodaconnect#48]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to set the charging speed and the off-peak period and the function (Charging or Clima), it would be nice to add this params to the skodaconnect.set_departure_schedule service

```
service: skodaconnect.set_departure_schedule
data:
  device_id: b4c63460cb2a42b8b6811bf24eab2782
  id: 1
  enabled: true
  recurring: true
  time: '8:30:00'
  days: yyyyyyy
```

**Describe the solution you'd like**

```
service: skodaconnect.set_departure_schedule
data:
  device_id: b4c63460cb2a42b8b6811bf24eab2782
  id: 1
  enabled: true
  recurring: true
  time: '8:30:00'
  days: yyyyyyy
  off_peak_start: '11:30:00'
  off_peak_end: '7:30:00'
  charging_speed: max
  clima: true
  charging: true
```

**Describe alternatives you've considered**

An alternative wolud be to create a new service to set only this params
